version: '3.8'
services:
  fast-data-dev:
    image: landoop/fast-data-dev:latest
    ports:
      - "2181:2181"
      - "3030:3030"
      - "3031:3031"
      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"
      - "9092-9093:9092-9093"
    environment:
      - "ENABLE_SSL=1"
      - "RUNTESTS=0"
      - "RUNNING_SAMPLEDATA=0"
      - "FORWARDLOGS=0"
      - "ADV_HOST=192.168.1.9"
      - "SSL_EXTRA_HOSTS=192.168.1.*"
